# Configuración para Base de Datos H2 (Local)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que podamos ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Crear tablas automáticamente

spring.jpa.show-sql=true

# Usa el puerto que te asigne la nube o el 8080 por defecto
server.port=${PORT:8080}

# Configuración de H2 para que persista en un archivo (opcional)
spring.datasource.url=jdbc:h2:file:./data/numisdb
spring.jpa.hibernate.ddl-auto=update